- name: Change hostname
  hostname:
    name: bastion

- name: upgrade all packages
  yum:
    name: "*"
    state: latest

# - name: Copy a new "ssh_config" file into place
#   template:
#     src: ssh_config.j2
#     dest: /etc/ssh/sshd_config
#     owner: root
#     group: root
#     mode: '0644'
#     backup: yes