- name: upgrade all packages
  yum:
    name: "*"
    state: latest

- name: install yum utils
  yum:
    name: "yum-utils"
    state: latest

- name: add docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install docker
  yum:
    name: "docker"
    state: latest

- name: add kubernetes repo
  yum_repository:
    name: Kubernetes
    description: kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    gpgcheck: no

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  ansible.posix.selinux:
    state: disabled

- name: install kubeadm, kubelet and kubectl
  yum:
    name:
      - kubectl
      - kubeadm
      - kubelet
    state: latest

- name: Activate br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present


- name: update kernel settings
  become: yes
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Start service kubelet
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes